version: '3.1'
services:
  stats-db:
    image: postgres:16.1-alpine
    container_name: stat_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-server:
    build: ./stats/stats-server
    image: stats-server
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=statsDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=stats-db
      - DB_PORT=5432
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsDb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    image: postgres:16.1-alpine
    container_name: ewm_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main-service
    image: ewm-service
    container_name: ewm_service_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - DB_NAME=ewm
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
